name: render

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check GPU Info
      run: |
        lspci | grep -i nvidia || true  # Check for NVIDIA GPU
        lspci | grep -i amd || true    # Check for AMD GPU
        glxinfo | grep "OpenGL renderer" || echo "No GPU detected" || true

    - name: Cache Blender
      id: cache-blender
      uses: actions/cache@v3
      with:
        path: blender-4.2.3-linux-x64
        key: blender-4.2.3-linux-x64

    - name: Install Blender
      if: steps.cache-blender.outputs.cache-hit != 'true'
      run: |
        wget https://download.blender.org/release/Blender4.2/blender-4.2.3-linux-x64.tar.xz
        tar xf blender-4.2.3-linux-x64.tar.xz

    - name: Cache file
      id: cache-file
      uses: actions/cache@v3
      with:
        path: TP_ht_new.blend
        key: TP_ht_new.blend

    - name: Download file
      if: steps.cache-file.outputs.cache-hit != 'true'
      run: |
        pip install gdown
        gdown --id 1q-7fO3GAeQMaEsZw3EqQBup3dCDsz8Dt -O TP_ht_new.blend

    - name: Render
      working-directory: ${{ github.workspace }}
      run: |
        mkdir -p render/
        ./blender-4.2.3-linux-x64/blender -b --python script.py
        ./blender-4.2.3-linux-x64/blender -b TP_ht_new.blend --python script.py -noaudio -o render/#### -E CYCLES -s 100 -e 105 -a -F 'PNG' -t 4
      
    - name: Upload result
      uses: 'actions/upload-artifact@v4'
      with:
        name: upload
        path: ${{ github.workspace }}/render

